import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Group02",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "orange",
            color: "white",
            padding: "1rem",
            fontSize: "1.5rem",
          }}
        >
          <p>Header</p>
        </header>
        <div className="p-4">
          {children}
        </div>
        
        <footer
          style={{
            backgroundColor: "green",
            color: "white",
            padding: "1rem",
            fontSize: "1.5rem",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
